name: buildprogrampython
on :
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: CheckOut
       uses: actions/checkout@v4
  
     - name: Set up python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'

     - name: Execute Script Python
       run: python ./helloworld.py
       
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with: 
          aws-access-key-id: 'AKIAWMP4EQGYFKTOA2MK'
          aws-secret-access-key: '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'
          aws-region: us-east-2 

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
       with:
          registry: 439152312752.dkr.ecr.us-east-2.amazonaws.com 
          aws-region: us-east-2
    
