name: buildprogrampython
on :
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: CheckOut
       uses: actions/checkout@v4
  
     - name: Set up python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'

     - name: Execute Script Python
       run: python ./helloworld.py
       
     - name: Login ECR AWS
       uses: docker/login-action@v3
       with:
          registry: 439152312752.dkr.ecr.us-east-2.amazonaws.com/recentral
          username: ${{ vars.AWS_ACCESS_KEY_ID }}
          password: ${{ var.AWS_SECRET_ACCESS_KEY }}  
    
