name: buildprogrampython
on:
  push:
    branches:
      - main
jobs:
  UploadPythonForce:
    runs-on: ubuntu-latest
    environment: ENVIRONMENTECR
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flask Dependency
        run: pip install Flask
        
      - name: Execute Script Python
        run: python ./helloworld.py
      

      - name: Install Docker
        uses: docker/setup-docker-action@v4

      - name: Validate Docker
        run: docker --version
