name: buildprogrampython
on :
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: CheckOut
       uses: actions/checkout@v4
  
     - name: Set up python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'

     - name: Execute Script Python
       run: python ./helloworld.py
       
     - name: Run Context Var Show
       run: echo "$GITHUB_CONTEXT"

      

  
    
