name: testingone
on:
  push:
    branches:
      - main
jobs:
  oidc-test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Obtener token OIDC
        run: |
          # Llamada al endpoint OIDC de GitHub para obtener el JWT
          TOKEN=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL?audience=sts.amazonaws.com")
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Asumir rol con web identity
        run: |
          aws sts assume-role-with-web-identity \
            --role-arn arn:aws:iam::439152132752:role/OIDCRoleHub \
            --role-session-name pruebaOIDC \
            --web-identity-token "$TOKEN" \
            --duration-seconds 900 > assume-output.json
          cat assume-output.json

      - name: Verificar credenciales temporales
        run: |
          jq .Credentials.AssumedRoleUser.Arn assume-output.json
