name: buildprogrampython
on:
  push:
    branches:
      - main

permissions:
 id-token: write
 contents: read
    
jobs:
  Producer:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::439152312752:role/rol-github-oidc
