name: Test OIDC Assume-Role
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  oidc-assume-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Obtener token OIDC de GitHub
        id: get_token
        run: |
          TOKEN=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL?audience=sts.amazonaws.com" \
            | jq -r '.value')
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Asumir rol con Web Identity
        id: assume_role
        run: |
          aws sts assume-role-with-web-identity \
            --role-arn arn:aws:iam::439152312752:role/IODCRoleHub \
            --role-session-name pruebaOIDC \
            --web-identity-token "${{ steps.get_token.outputs.token }}" \
            --duration-seconds 900 \
            --output json > assume-output.json
          cat assume-output.json

      - name: Verificar credenciales temporales
        run: |
          echo "ARN del rol asumido:"
          jq -r .AssumedRoleUser.Arn assume-output.json
          echo "Expiration:"
          jq -r .Credentials.Expiration assume-output.json
