name: buildprogrampython
on:
  push:
    branches:
      - test

permissions:
 id-token: write
 contents: read
    
jobs:
  Producer:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut OIDC
      
